version: '3.8'

services:

  neo4j:
    image: neo4j:5.14
    container_name: orquesta-neo4j
    environment:
      - NEO4J_AUTH=neo4j/test1234
    ports:
      - "7474:7474"   # Neo4j Browser
      - "7687:7687"   # Bolt (usado por la app Spring)
    volumes:
      - neo4j-data:/data
    restart: unless-stopped

  zookeeper:
    image: zookeeper:3.8
    container_name: orquesta-zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped

volumes:
  neo4j-data:
